// Code generated by roundtripgen; DO NOT EDIT.

package fuzz

import (
	v1alpha1 "github.com/prysmaticlabs/prysm/v5/proto/prysm/v1alpha1"
	"testing"
)

func FuzzAttestationRoundTrip(f *testing.F) {
	runRoundTripFuzz[v1alpha1.Attestation, *v1alpha1.Attestation](f, "Attestation")
}

func FuzzBeaconBlockBodyRoundTrip(f *testing.F) {
	runRoundTripFuzz[v1alpha1.BeaconBlockBody, *v1alpha1.BeaconBlockBody](f, "BeaconBlockBody")
}

func FuzzSignedBeaconBlockRoundTrip(f *testing.F) {
	runRoundTripFuzz[v1alpha1.SignedBeaconBlock, *v1alpha1.SignedBeaconBlock](f, "SignedBeaconBlock")
}

func FuzzIndexedAttestationRoundTrip(f *testing.F) {
	runRoundTripFuzz[v1alpha1.IndexedAttestation, *v1alpha1.IndexedAttestation](f, "IndexedAttestation")
}
