package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"alma.local/ssz/internal/targets"
)

func main() {
	var (
		configPath string
		outputPath string
	)
	flag.StringVar(&configPath, "config", "", "path to roundtrip target list (JSON)")
	flag.StringVar(&outputPath, "output", "", "where to write the generated fuzz file")
	flag.Parse()

	if configPath == "" {
		fatal("missing -config")
	}
	if outputPath == "" {
		fatal("missing -output")
	}

	rtTargets, err := targets.LoadRoundTripTargets(configPath)
	if err != nil {
		fatal("load targets: %v", err)
	}
	if len(rtTargets) == 0 {
		fatal("config contained no targets")
	}

	importAliases := map[string]string{}
	aliasUsed := map[string]bool{}
	baseCounts := map[string]int{}
	for _, t := range rtTargets {
		if t.Name == "" || t.ImportPath == "" || t.Type == "" {
			fatal("invalid target: %+v", t)
		}
		if _, ok := importAliases[t.ImportPath]; ok {
			continue
		}
		base := filepath.Base(t.ImportPath)
		base = sanitizeIdent(base)
		alias := base
		for aliasUsed[alias] {
			baseCounts[base]++
			alias = fmt.Sprintf("%s%d", base, baseCounts[base])
		}
		aliasUsed[alias] = true
		importAliases[t.ImportPath] = alias
	}

	sortedImports := make([]string, 0, len(importAliases))
	for impPath := range importAliases {
		sortedImports = append(sortedImports, impPath)
	}
	sort.Strings(sortedImports)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by roundtripgen; DO NOT EDIT.\n\n")
	buf.WriteString("package fuzz\n\n")
	buf.WriteString("import (\n\t\"testing\"\n")
	for _, imp := range sortedImports {
		fmt.Fprintf(&buf, "\t%s \"%s\"\n", importAliases[imp], imp)
	}
	buf.WriteString(")\n\n")

	for _, t := range rtTargets {
		alias := importAliases[t.ImportPath]
		fmt.Fprintf(&buf, "func Fuzz%sRoundTrip(f *testing.F) {\n", t.Name)
		fmt.Fprintf(&buf, "\trunRoundTripFuzz[%s.%s, *%s.%s](f, %q)\n", alias, t.Type, alias, t.Type, t.Name)
		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fatal("format output: %v", err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fatal("write output: %v", err)
	}
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "pkg"
	}
	return b.String()
}

func fatal(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "roundtripgen: "+format+"\n", args...)
	os.Exit(1)
}
